-- 004_extend_leads.sql
-- Add new columns to the existing leads table

ALTER TABLE leads ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS job_title VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS product_type VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS product_type_2 VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS product_type_3 VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS square_footage FLOAT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS custom_pick_1 VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS project_city VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS project_type VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS business_category VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS dealer_email VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS form_submit_date TIMESTAMP;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_source VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS opt_in BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS landing_page VARCHAR(500);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS landing_page_url VARCHAR(500);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS landing_page_variant VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_source VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_medium VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_campaign VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_content VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_term VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS custom_pick_3 VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS value_of_order DECIMAL(12,2);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_dealer_id INTEGER REFERENCES dealers(id);
